### ISSUE TITLE
Update of Release Notes for releases containing breaking changes

### ISSUE THREAD

**Issue by TheDestinyGroup** [alecgn/crypthash-net#10]
Alessandro,

Can I suggest that where there are breaking changes in the encryption/decryption between releases that this is expressly mention that in the Release Notes for those releases on the Releases page.

I feel that this should be clearly mentioned in the release notes as merely updating the major version number (as per Semantic Versioning) is probably insufficient when it comes to making end users aware that files data/files encrypted by an earlier release can no longer be decrypted by this release.

End users often depend on the release notes to determine the impact on their project when evaluating whether they should to update to a new release.

This is because most open source developers / projects fail to state whether they're project uses Semantic Versioning or some other approach to versioning and most commercial developers update the major version number as a way to different between paid and free updates regardless of whether the update contains breaking changes.

I would even suggest it should you mention in the ReadMe that version 3.x is incompatible with previous releases and your thoughts/policy with respect to breaking changes going forward as this type of disclosure will give end users some confidence in using your library going forward.

Les

**Comment by alecgn** [comment]
Great notes. It will be done as soon as possible.

**Comment by alecgn** [comment]
Done.

**Comment by TheDestinyGroup** [comment]
Alessandro,

Thanks for listening.

End users such as myself often depend on the release notes to determine the impact on their project when evaluating whether they should to update to a new release.

This is because most open source developers / projects fail to state whether they're project uses Semantic Versioning or some other approach to versioning and most commercial developers update the major version number as a way to different between paid and free updates regardless of whether the update contains breaking changes to their library.

I would still suggest that you update the ReadMe to clearly state that this project uses Semantic Versioning, that version 3 won't be able to decrypt data and files encrypted with versions 1 or 2 and your thoughts/policy with respect to breaking changes going forward as this type of disclosure will give end users some confidence in using your library going forward.

I say this because unlike other projects, a breaking change in your project doesn't just mean someone will need to update their code as is implied when changing the major version number with Semantic Versioning, it also means they may not be able to decrypt data or files encrypted with an earlier major release which is an important distinction.

Les

**Comment by TheDestinyGroup** [comment]
Alessandro,

Thanks for listening and updating the ReadMe.

Les

**Comment by alecgn** [comment]
You're welcome Les.

I've been working a lot last days, almost no time to keep things up to date around here.
