### ISSUE TITLE
Use of encryptedFilePath variable name in DecryptFile functions

### ISSUE THREAD

**Issue by TheDestinyGroup** [alecgn/crypthash-net#11]
Alessandro,

I think the variable name "encryptedFilePath" in the DecryptFile functions that accept sourceFilePath and encryptedFilePath should be replaced with "decryptedFilePath" as it's extremely confusing when the "encryptedFilePath" variable from these functions gets passed to the "decryptedFilePath" variable on the function that does the actual decryption.

Furthermore I think it would be logical to replace the variable name "sourceFilePath" in those same functions with "encryptedFilePath" so their variables are consistent with function that does the actual decryption.

Les

**Comment by alecgn** [comment]
Fixeb by https://github.com/alecgn/crypthash-net/commit/4b2f8057b163b8cb0922aa2efc13b30cf8932e40
