### ISSUE TITLE
Use of aesDecriptionResult and aesDecryptionResult variables

### ISSUE THREAD

**Issue by TheDestinyGroup** [alecgn/crypthash-net#12]
Alessandro,

I think that the use of the variables "aesDecriptionResult" and "aesDecryptionResult" should be replaced with "AesEncryptionResult" for project consistency.

Alternatively you could add a "aesDecryptionResult" class and change the DecryptString and DecryptFile functions be of a "aesDecryptionResult" type and then update the "AesEncryptionResult" class to remove the fields related to decryption.

At the very least I think "aesDecriptionResult" should be replaced with "aesDecryptionResult" as I think that was a typo.

Les

**Comment by alecgn** [comment]
Fixed by https://github.com/alecgn/crypthash-net/commit/4b2f8057b163b8cb0922aa2efc13b30cf8932e40
