### ISSUE TITLE
Encryption on newest versions doesn't work.

### ISSUE THREAD

**Issue by PTerentev** [alecgn/crypthash-net#16]
I have tried to use encryption on newest version (3.3.5) but got the problem.
![335](https://user-images.githubusercontent.com/37480628/71728766-f46da100-2e78-11ea-808c-4771cc964901.jpg)
.Net Framework version  - 4.6.2
On version 3.3.0 all is working fine.

**Comment by alecgn** [comment]
Thanks by feedback @PTerentev, will verify this issue asap.

**Comment by PTerentev** [comment]
i've found that problem appears only by the dll from nuget package, i changed dependences from the project to dll from nuget. 
![image](https://user-images.githubusercontent.com/37480628/71732344-f6882d80-2e81-11ea-8480-8c1a672eb690.png)

**Comment by alecgn** [comment]
I've tested here using the same environment configuration then yours (.NET Framework 4.6.2), everything works fine. Did you ensured your  parameter "message" is not null?

**Comment by PTerentev** [comment]
Have you tested on version from nuget?

**Comment by alecgn** [comment]
Yes, both versions 3.3.0 and 3.3.5, everything working fine.

![print_1](https://user-images.githubusercontent.com/15014190/71733800-31aa4280-2e29-11ea-8bfd-9ecca1b8c8a4.PNG)
![print_2](https://user-images.githubusercontent.com/15014190/71733801-3242d900-2e29-11ea-8fe3-d578c429a5b2.PNG)
![print_3](https://user-images.githubusercontent.com/15014190/71733803-3242d900-2e29-11ea-8752-90094bf42073.PNG)

**Comment by PTerentev** [comment]
Hmm.. Im getting this one on 3.3.5 (tested on 2 PCs) 
![image](https://user-images.githubusercontent.com/37480628/71734350-b9726a00-2e86-11ea-92b9-1c0a4fd18a19.png)

**Comment by alecgn** [comment]
Maybe .NET Framework (aka Full-Framework) 4.6.2 suffers from the same issues than 4.6.1, but I will investigate this situation in depth. For now, if you can, try update your version and please verify if the error persists...
![Screenshot_1](https://user-images.githubusercontent.com/15014190/71737907-cd40b080-2e33-11ea-91e1-7403622d04a3.png)

**Comment by PTerentev** [comment]
I`ve found the cause. It's all because of this line. Its throwing an error because my PC doesn't have this directory. The line only exists in nuget dll, not in the git hub code.
![image](https://user-images.githubusercontent.com/37480628/71739998-f2660b00-2e95-11ea-815e-4416d6ea2a7b.png)

**Comment by alecgn** [comment]
Oh my God, it looks like this line that was just a test was shipped in build-release on version 3.3.5. Sorry for that, I'm going to inspect all the source and draft a new Nuget release 3.3.6 okay. Thanks for finding this terrible thing.

**Comment by alecgn** [comment]
NuGet package updated -> https://www.nuget.org/packages/CryptHash.Net/3.3.6; still some minutes to get listed.
