### ISSUE TITLE
AES-128-GCM supported?

### ISSUE THREAD

**Issue by GF-Huang** [alecgn/crypthash-net#18]

**Comment by alecgn** [comment]
@GF-Huang, currently only AES_256_GCM is supported. I'm gonna add support for AES_128_GCM.

**Comment by GF-Huang** [comment]
Thanks. 🌹

**Comment by alecgn** [comment]
@GF-Huang done. NuGet package available in -> https://www.nuget.org/packages/CryptHash.Net/3.5.0

**Comment by GF-Huang** [comment]
Great, Thanks a lot. 👍
