### ISSUE TITLE
Ongoing support for .Net Framework 4.7.x and 4.8 (.Net Standard 2.0)

### ISSUE THREAD

**Issue by TheDestinyGroup** [alecgn/crypthash-net#2]
Alessandro,

It seems that project development is primary focused on .Net Standard 2.1 and .Net Core 3.0.

Do you intent to continue supporting .Net Framework 4.7.x and 4.8 (.Net Standard 2.0) for the foreseeable future?

I would like to start using your library but as we have a legacy Asp.Net solution which currently targets .Net Framework 4.7.2 we need a library that will at least continue to support .Net Framework 4.7.x and 4.8 (.Net Standard 2.0) into the foreseeable future as it'll take us a couple of years to complete rewriting the solution to target Asp.Net Core.

Les

**Comment by alecgn** [comment]
Hello!

CryptHash.Net is a multi-target project for .NET Standard 2.0, 2.1 and .NET Core 3.0.
All classes and methods, but AES-GCM and some functions of "EncryptionUtils.cs", are fully compatible with .NET Standard 2.0 (.NET Framework 4.7.x and 4.8), but unfortunately only .NET Standard 2.1/.NET Core 3.0 has native support for AES-GCM encryption. Maybe in the future I could implement a .NET Standard 2.0 compatible code using the Bouncy Castle library, I'll put that in plans.
But in short, yes, .NET Standard 2.0 compatibility will be manteined.

**Comment by TheDestinyGroup** [comment]
Alessandro,

Thanks for the response.

I don't perceive an issue with AES-GCM being .NET Core 3.0 specific as I'm aware of the lack of support for AES-GCM in the other platforms.

I was more concerned about the ongoing support for the .NET Standard 2.0 for those features your library currently supports on .NET Standard 2.0.

Les
