### ISSUE TITLE
Typo in one of the variable names of DecryptFile

### ISSUE THREAD

**Issue by TheDestinyGroup** [alecgn/crypthash-net#9]
Alessandro,

I was reviewing the changes in commit 87e8a8e when I noticed that there appears to be a typo in one of the variable names in the calls to DecryptFile in the Tests.

I think "hasEncryptionDataAppendedInIntputFile" is meant to be "hasEncryptionDataAppendedInInputFile"

After pulling down a copy of the project and reviewing further within VS it appears that this Typo occurs in the DecryptFile variable names throughout the project.

Les

**Comment by alecgn** [comment]
Fixed by https://github.com/alecgn/crypthash-net/commit/4b2f8057b163b8cb0922aa2efc13b30cf8932e40
